/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_WAYPOINTSERVERSTUB_H_
#define JSONRPC_CPP_STUB_WAYPOINTSERVERSTUB_H_

#include <jsonrpccpp/server.h>

class waypointserverstub : public jsonrpc::AbstractServer<waypointserverstub>
{
    public:
        waypointserverstub(jsonrpc::AbstractServerConnector &conn, jsonrpc::serverVersion_t type = jsonrpc::JSONRPC_SERVER_V2) : jsonrpc::AbstractServer<waypointserverstub>(conn, type)
        {
            this->bindAndAddMethod(jsonrpc::Procedure("saveToJsonFile", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_BOOLEAN,  NULL), &waypointserverstub::saveToJsonFileI);
            this->bindAndAddMethod(jsonrpc::Procedure("resetFromJsonFile", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_BOOLEAN,  NULL), &waypointserverstub::resetFromJsonFileI);
            this->bindAndAddMethod(jsonrpc::Procedure("add", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_BOOLEAN, "param1",jsonrpc::JSON_OBJECT, NULL), &waypointserverstub::addI);
            this->bindAndAddMethod(jsonrpc::Procedure("remove", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_BOOLEAN, "param1",jsonrpc::JSON_OBJECT, NULL), &waypointserverstub::removeI);
            this->bindAndAddMethod(jsonrpc::Procedure("mod", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_BOOLEAN, "param1",jsonrpc::JSON_STRING,"param2",jsonrpc::JSON_REAL,"param3",jsonrpc::JSON_REAL,"param4",jsonrpc::JSON_REAL,"param5",jsonrpc::JSON_STRING,"param6",jsonrpc::JSON_STRING, NULL), &waypointserverstub::modI);
            this->bindAndAddMethod(jsonrpc::Procedure("get", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_ARRAY, "param1",jsonrpc::JSON_STRING, NULL), &waypointserverstub::getI);
            this->bindAndAddMethod(jsonrpc::Procedure("bearing", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_REAL, "param1",jsonrpc::JSON_STRING,"param2",jsonrpc::JSON_STRING, NULL), &waypointserverstub::bearingI);
            this->bindAndAddMethod(jsonrpc::Procedure("distance", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_REAL, "param1",jsonrpc::JSON_STRING,"param2",jsonrpc::JSON_STRING, NULL), &waypointserverstub::distanceI);
        }

        inline virtual void saveToJsonFileI(const Json::Value &request, Json::Value &response)
        {
            (void)request;
            response = this->saveToJsonFile();
        }
        inline virtual void resetFromJsonFileI(const Json::Value &request, Json::Value &response)
        {
            (void)request;
            response = this->resetFromJsonFile();
        }
        inline virtual void addI(const Json::Value &request, Json::Value &response)
        {
            response = this->add(request[0u]);
        }
        inline virtual void removeI(const Json::Value &request, Json::Value &response)
        {
            response = this->remove(request[0u]);
        }
        inline virtual void modI(const Json::Value &request, Json::Value &response)
        {
            response = this->mod(request[0u].asString(), request[1u].asDouble(), request[2u].asDouble(), request[3u].asDouble(), request[4u].asString(), request[5u].asString());
        }
        inline virtual void getI(const Json::Value &request, Json::Value &response)
        {
            response = this->get(request[0u].asString());
        }
        inline virtual void bearingI(const Json::Value &request, Json::Value &response)
        {
            response = this->bearing(request[0u].asString(), request[1u].asString());
        }
        inline virtual void distanceI(const Json::Value &request, Json::Value &response)
        {
            response = this->distance(request[0u].asString(), request[1u].asString());
        }
        virtual bool saveToJsonFile() = 0;
        virtual bool resetFromJsonFile() = 0;
        virtual bool add(const Json::Value& param1) = 0;
        virtual bool remove(const Json::Value& param1) = 0;
        virtual bool mod(const std::string& param1, double param2, double param3, double param4, const std::string& param5, const std::string& param6) = 0;
        virtual Json::Value get(const std::string& param1) = 0;
        virtual double bearing(const std::string& param1, const std::string& param2) = 0;
        virtual double distance(const std::string& param1, const std::string& param2) = 0;
};

#endif //JSONRPC_CPP_STUB_WAYPOINTSERVERSTUB_H_
